name: turnip-android-build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'select branch to build(default: master)'
        required: false
        default: 'main'
  schedule:
    - cron: '0 0 * * *'

jobs:
  start_building_turnip:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with: { ref: master }

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y
        sudo sed -i 's/jammy/mantic/g' /etc/apt/sources.list
        sudo apt update
        sudo apt install meson
    
    - name: Execute build script
      run: bash ./turnip_builder.sh ${{ github.event.inputs.branch }}
      
    - id: version
      name: Get version
      run: |
          echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_OUTPUT

    - name: Release ${{ steps.version.outputs.date }}
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.version.outputs.date }}
        tag_name: ${{ steps.version.outputs.date }}
        body: Turnip Android module
        files: |
           turnip_workdir/turnip_${{ steps.version.outputs.date }}.zip
